# Generated by Django 5.0.1 on 2024-02-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('extra', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=25)),
                ('foodname', models.CharField(max_length=25)),
                ('howmuch', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
