# Generated by Django 5.0.2 on 2024-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('website', models.CharField(max_length=25)),
                ('mobileno', models.IntegerField()),
            ],
        ),
    ]
