# Generated by Django 5.0.2 on 2024-02-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobileno',
        ),
    ]
