# Generated by Django 5.0.2 on 2024-02-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_feedback_remove_contact_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobileno',
            field=models.IntegerField(null=True),
        ),
    ]
